export const SITE_CONTENT = {
  businessName: 'SNV Automobile (UK) Ltd',
  tagline: 'Your Automotive Repair & Maintenance Service Specialist',
  phone: '07958 319821',
  whatsapp: '+447958319821',
  email: '',
  address: '80B Malvern Gardens, London HA3 9PG',
  city: 'Harrow',
  country: 'United Kingdom',
  hours: {
    weekdays: 'Mon-Fri: 8:00 AM - 7:00 PM',
    saturday: 'Saturday: 8:00 AM - 7:00 PM',
    sunday: 'Sunday: 8:00 AM - 7:00 PM',
  },
  rating: {
    value: 5.0,
    count: 13,
  },
  services: [
    {
      id: 'preventative',
      title: 'Preventative Maintenance',
      description: 'The best way to minimize breakdowns is doing routine maintenance',
      icon: 'maintenance',
    },
    {
      id: 'common',
      title: 'Most Common Repairs',
      description: 'We have over 30 common car repairs and the list is growing',
      icon: 'common',
    },
    {
      id: 'brake',
      title: 'Brake Repair & Service',
      description:
        'Brake maintenance is important in helping ensure the safety of you and your passengers',
      icon: 'brake',
    },
  ],
  repairServices: [
    'FREE Shuttle Service',
    'General Auto Repair & Maintenance',
    'Transmission Repair & Replacement',
    'Fuel System Repair',
    'Exhaust System Repair',
    'Engine Cooling System Maintenance',
    'Electrical Diagnostics',
    'Starting and Charging Repair',
    'Wheel Alignment',
    'CV Axles',
    'Computer Diagnostic Testing',
    'Manufacturer Recommended Service',
    'Brake Repair and Replacement',
    'Air Conditioning A/C Repair',
    'Tire Repair and Replacement',
    'Vehicle Preventative Maintenance',
    'State Emissions Inspection',
    'Emission Repair Facility',
    'Tune Up',
    'Oil Change',
    'Brake Job / Brake Service',
    'Engine Cooling System Flush & Repair',
    'Steering and Suspension Work',
  ],
  guarantees: [
    '24 Month / 24,000km Nationwide Warranty',
    'Courtesy Local Shuttle Service',
    'Customer Rewards Program',
    'ASE Certified Technicians',
    '24-Hour Roadside Assistance',
    'Courtesy Loaner Vehicle',
  ],
  stats: {
    yearsExperience: 20,
    vehiclesRepaired: '2.9K',
    technicians: 32,
    satisfaction: '100%',
  },
};
